[target.x86_64-unknown-linux-gnu]
rustflags = ["-L", "__REPO_ROOT__/build/lib/x86_64-unknown-linux-gnu"]

[target.aarch64-unknown-linux-gnu]
rustflags = ["-L", "__REPO_ROOT__/build/lib/aarch64-unknown-linux-gnu"]
